export const LoremIpsum = `Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque tempor est sit amet metus dignissim cursus sed eget augue. Phasellus non ante viverra, euismod mi eget, convallis odio. Nunc lobortis consequat bibendum. Nunc quis sapien facilisis, consectetur metus eu, luctus dui. In hac habitasse platea dictumst. Maecenas convallis aliquet fringilla. Integer lobortis odio massa, a pharetra nisl lobortis tincidunt.

Ut gravida augue purus, ut finibus purus pulvinar ac. Vestibulum luctus vitae libero quis tempor. Phasellus vitae libero felis. Phasellus maximus nisl sed dolor scelerisque viverra. Nulla eu nisl lacus. Integer quis mauris velit. Phasellus blandit finibus lorem.

Proin feugiat elit sit amet risus bibendum finibus. Donec fringilla massa sed consequat tempus. Nullam porta ligula mi, vel ullamcorper sem hendrerit ac. Vivamus eget semper risus, in laoreet ante. Aliquam elementum maximus velit scelerisque rutrum. Nullam nunc nisi, commodo vehicula accumsan accumsan, convallis non tortor. Fusce ut mattis nisl. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce est diam, ornare id dolor eu, rhoncus sagittis tellus. Vivamus quis mauris vel mauris commodo porttitor. Nunc fermentum lorem vitae lectus lobortis interdum.

Pellentesque ut mollis tortor. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Praesent dapibus id massa sed aliquet. Morbi eu tortor vel magna finibus blandit sit amet sit amet quam. Phasellus a finibus dolor. Nunc libero ante, cursus sed tellus id, commodo tempus odio. Mauris ornare urna tellus, vel aliquam magna vehicula eu. Nam ut eros ut ipsum scelerisque dictum in et dolor. Sed id luctus mi. Donec eget odio scelerisque, bibendum erat a, consequat ex. Donec quis orci urna. Aenean pellentesque vel erat ac dignissim. Cras suscipit nulla urna, vel tincidunt felis suscipit nec.

Proin quis fermentum magna. Duis ac erat vitae mi sollicitudin pretium. Interdum et malesuada fames ac ante ipsum primis in faucibus. Ut finibus risus ac turpis hendrerit, sed aliquam diam mollis. Etiam facilisis sollicitudin sem, nec varius justo gravida in. Nunc fermentum felis et fringilla dapibus. Morbi nulla elit, mollis eget eros ut, accumsan mattis justo. Nunc magna dolor, tempus vitae urna placerat, imperdiet egestas magna. Nulla aliquet tellus in enim viverra, at elementum turpis tristique. Donec et auctor mauris. Proin nec tincidunt nibh. Suspendisse tincidunt elit vel magna rhoncus sollicitudin. Nam porttitor sapien ut viverra finibus. Aliquam lacinia orci odio, non mattis quam condimentum at. In ac interdum nibh. Quisque ut posuere quam.`;
